name: Deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHubActions-CDK-${{ github.run_number }}

      - name: list S3 Buckets
        env:
          AWS_REGION: ${{ secrets.AWS_REGION}}
        run: |
          echo "Listing S3 Buckets"
          aws s3 ls

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install infra dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./infra

      - name: Bootstrap CDK (if needed)
        # run: cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID }}/${{ secrets.AWS_REGION }}
        run: cdk bootstrap
        working-directory: ./infra

      - name: Synth and Deploy CDK stack
        run: |
          cdk synth
          cdk deploy --all --require-approval never
        working-directory: ./infra
