name: Deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: "10.0.0"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHubActions-CDK-${{ github.run_number }}

      - name: list S3 Buckets
        env:
          AWS_REGION: ${{ secrets.AWS_REGION}}
        run: |
          echo "Listing S3 Buckets"
          aws s3 ls

    #   - name: Install dependencies
    #     run: pnpm install --frozen-lockfile

    #   - name: Install CDK
    #     run: pnpm add -g aws-cdk

    #   - name: Bootstrap CDK (if needed)
    #     run: cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID }}/${{ env.AWS_REGION }}

    #   - name: Synth and Deploy
    #     run: |
    #       cdk synth
    #       cdk deploy --require-approval never
