name: Destroy CDK Stack

on:
  workflow_dispatch: # Allows manual triggering

permissions:
  id-token: write # Required for AWS authentication
  contents: read # Required to checkout code

jobs:
  destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Match your CDK version's Node requirement

      - name: Install dependencies
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }} # Your IAM role ARN
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Destroy CDK stack
        run: npx cdk destroy --force
    #   env:
    #     DOMAIN_NAME: ${{ env.DOMAIN_NAME }}
    #     BUCKET_NAME: ${{ env.BUCKET_NAME }}
