name: Destroy

on:
  workflow_dispatch: # Allows manual triggering

permissions:
  id-token: write # Required for AWS authentication
  contents: read # Required to checkout code

jobs:
  destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22" # or your preferred version

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install infra dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./infra

      - name: Install cdk
        run: npm install -g aws-cdk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHubActions-CDK-${{ github.run_number }}

      - name: Destroy CDK stack
        run: cdk destroy --force
        working-directory: ./infra
